#.libPaths(c(.libPaths(), "/home/gpscom/R/x86_64-pc-linux-gnu-library/3.2"))
library(readr)
library(igraph)
library(RColorBrewer)
library(plyr)
library(dplyr)
library(ggplot2)
library(scales)
library(RMySQL)
library(gtools)
significance <- read.csv(file = "significance.csv", sep = ";")
calculaMetricas()