#.libPaths(c(.libPaths(), "/home/gpscom/R/x86_64-pc-linux-gnu-library/3.2"))
#args <- commandArgs(trailingOnly = TRUE)
#i <- as.numeric(args[1])
#f <- as.numeric(args[2])
#i <- 1
#f <- 5
#significance <- read.csv(file = "significance.csv", sep = ";")
#calculaMetricas(i, f)
args <- commandArgs(trailingOnly = TRUE)
i <- as.numeric(args[1])
f <- as.numeric(args[2])
message("Init projects ",i," to ",f)
source(file = "TurnoverAnalysis10.R")
#create.data.network()
#create.data.sentiment()
create.metrics()